# Generated by Django 5.2 on 2025-06-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='news_datas',
        ),
    ]
